services:
  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_DB: snippetsdb
      POSTGRES_USER: snippetuser
      POSTGRES_PASSWORD: snippetpassword
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: ./
    container_name: spring_boot_app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/snippetsdb
      SPRING_DATASOURCE_USERNAME: snippetuser
      SPRING_DATASOURCE_PASSWORD: snippetpassword
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  pgdata: